### ISSUE TITLE
Incomplete file transfer.

### ISSUE THREAD

**Issue by Haimonti** [seemoo-lab/opendrop#102]
I am trying to transfer a text file between two mac books. 

Opendrop find works as expected -- 
./opendrop find
Looking for receivers. Press Ctrl+C to stop ...
/Users/haimonti/Library/Python/3.9/lib/python/site-packages/zeroconf/_services/browser.py:168: FutureWarning: <opendrop.client.AirDropBrowser object at 0x1043857c0> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.
  warnings.warn(
Found  index 0  ID 242435eddd0c  name Haimonti Dutta’s iPhone
Found  index 1  ID bb3502543837  name jac325p-duttaOLD

But opendrop send gives an error after asking the receiver to accept, receiver accepted, and uploading file.
In particular, here is the error:

./opendrop send -r 0 -f /Users/haimonti/Research/DDM/DistMomMethods/test.txt
Asking receiver to accept ...
Receiver accepted
Uploading file ...
Exception ignored in: <function ArchiveEntry.__del__ at 0x102dd1c10>
Traceback (most recent call last):
  File "/Users/haimonti/Library/Python/3.9/lib/python/site-packages/libarchive/entry.py", line 51, in __del__
    ffi.entry_free(self._entry_p)
AttributeError: _entry_p
Traceback (most recent call last):
  File "/Users/haimonti/Library/Python/3.9/bin/./opendrop", line 8, in <module>
    sys.exit(main())
  File "/Users/haimonti/Library/Python/3.9/lib/python/site-packages/opendrop/cli.py", line 36, in main
    AirDropCli(sys.argv[1:])
  File "/Users/haimonti/Library/Python/3.9/lib/python/site-packages/opendrop/cli.py", line 112, in __init__
    self.send()
  File "/Users/haimonti/Library/Python/3.9/lib/python/site-packages/opendrop/cli.py", line 196, in send
    if not self.client.send_upload(self.file, is_url=self.is_url):
  File "/Users/haimonti/Library/Python/3.9/lib/python/site-packages/opendrop/client.py", line 214, in send_upload
    archive.add_abs_file(f, os.path.join(".", ff))
  File "/Users/haimonti/Library/Python/3.9/lib/python/site-packages/opendrop/util.py", line 184, in add_abs_file
    entry = ArchiveEntry(None, entry_p)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

Any suggestions would be very helpful. Thanks much in advance.

**Comment by takayanamba99** [comment]
I have the same problem when I tried to transfer the file between two mac books of Monterey.
Airdors are working well between the two mac books.
Any suggestions will help me.

**Comment by lucasromeiro** [comment]
@takayanamba99 @Haimonti 
Hi, Do you solve this?
 
I'm having trouble extracting keys from my Mac Studio.  did you have any problems?  
can you give me any tips?  

thank you for any help.

**Comment by takayanamba99** [comment]
I couldn't solve the problem, I am afraid.
I need someone's suggestion.

**Comment by Atemu** [comment]
Fixed by https://github.com/seemoo-lab/opendrop/pull/95
