### ISSUE TITLE
Can't discover devices

### ISSUE THREAD

**Issue by midozalouk** [seemoo-lab/opendrop#104]
i have the following problem related to the os i use
i am running chromeos and used homecrew to install owl
i have a strange poblem with opendrop
although new devices are found in owl 
but i can't discover them or finding them with the following error message

`/usr/local/lib64/python3.10/site-packages/zeroconf/_services/browser.py:179: FutureWarning: <opendrop.client.AirDropBrowser object at 0x7ae7ba49ef20> has no update_service method. Provide one (it can be empty if you don't care about the updates), it'll become mandatory.
  warnings.warn(

Exception in thread Thread-3 (_send_discover):
Traceback (most recent call last):
  File "/usr/local/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/opendrop/cli.py", line 156, in _send_discover
    receiver_name = client.send_discover()
  File "/usr/local/lib/python3.10/site-packages/opendrop/client.py", line 141, in send_discover
    _, response_bytes = self.send_POST("/Discover", discover_plist_binary)
  File "/usr/local/lib/python3.10/site-packages/opendrop/client.py", line 115, in send_POST
    self.http_conn.request("POST", url, body=body, headers=_headers)
  File "/usr/local/lib64/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib64/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib64/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib64/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib64/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib64/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/local/lib64/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.10/site-packages/opendrop/client.py", line 318, in create_connection_awdl
    raise err
  File "/usr/local/lib/python3.10/site-packages/opendrop/client.py", line 308, in create_connection_awdl
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
^Cmunmap_chunk(): invalid pointer`

how to solve it

**Comment by lucasromeiro** [comment]
Hi, Do you solve this?
 
I'm having trouble extracting keys from my Mac Studio.  did you have any problems?  
can you give me any tips?  

thank you for any help.

**Comment by lucasromeiro** [comment]
Hello everyone, this happened in the first step to get the keys:

![image](https://user-images.githubusercontent.com/2086543/220122693-248d8527-7e56-4ffd-805a-50d6554b6e27.png)


I continued the tutorial normally, but when I run the make command I get this error:

![image](https://user-images.githubusercontent.com/2086543/220122869-6bb240a3-a9cc-489c-8232-8946c903fa0f.png)


Can someone help me?

My MAC is a MacStudio with M1 Max and MAC OS 13.1 (22C65) (ventura).


Please, help...
