### ISSUE TITLE
opendrop find : ValueError: You must specify a valid interface name.

### ISSUE THREAD

**Issue by AnywherePear** [seemoo-lab/opendrop#12]
I tried this from a ubuntu 19.04 laptop...

$ opendrop find 

Looking for receivers. Press enter to stop ...
Traceback (most recent call last):
  File "/home/user1/.local/bin/opendrop", line 10, in <module>
    sys.exit(main())
  File "/home/user1/.local/lib/python3.7/site-packages/opendrop/cli.py", line 38, in main
    AirDropCli(sys.argv[1:])
  File "/home/user1/.local/lib/python3.7/site-packages/opendrop/cli.py", line 78, in __init__
    self.find()
  File "/home/user1/.local/lib/python3.7/site-packages/opendrop/cli.py", line 97, in find
    self.browser = AirDropBrowser(self.config)
  File "/home/user1/.local/lib/python3.7/site-packages/opendrop/client.py", line 48, in __init__
    self.ip_addr, self.byte_address = AirDropUtil.get_ip_for_interface(self.ip_interface_name, ipv6=self.useIPv6)
  File "/home/user1/.local/lib/python3.7/site-packages/opendrop/util.py", line 229, in get_ip_for_interface
    addresses = netifaces.ifaddresses(interface_name)
ValueError: You must specify a valid interface name.

**Comment by mjhough** [comment]
You need this https://github.com/seemoo-lab/owl

**Comment by zdavatz** [comment]
I installed _OWL_ but I still get the same error.

**Comment by mjhough** [comment]
@zdavatz You also need to start it.
