### ISSUE TITLE
OSError: [Errno 65] No route to host

### ISSUE THREAD

**Issue by Andrei07082023** [seemoo-lab/opendrop#123]
I am able to discover and receive files from my apple devices, but when i try to send a file or anything else i get the following error (i run opendrop on a MacBook with OSx 15):

Traceback (most recent call last):
  File "/__main__.py", line 22, in <module>
    cli1.main()
  File "/cli.py", line 36, in main
    AirDropCli(sys.argv[1:])
  File "/cli.py", line 114, in __init__
    self.send()
  File "/cli.py", line 193, in send
    if not self.client.send_ask(self.file, is_url=self.is_url):
  File "/client.py", line 189, in send_ask
    success, _ = self.send_POST("/Ask", ask_binary)
  File "/client.py", line 115, in send_POST
    self.http_conn.request("POST", url, body=body, headers=_headers)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1417, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/client.py", line 322, in create_connection_awdl
    raise err
  File "/client.py", line 312, in create_connection_awdl
    sock.connect(sa)
OSError: [Errno 65] No route to host

Has anyone encountered this?

**Comment by sorry-i-am-late** [comment]
I fear this project may be mostly abandoned. Hopefully it isnt but who knows.

I only found this today so if i get around to building it i will let you know if i have this issue

**Comment by OM-3kChcBjgFR2COfP** [comment]
Same problem too, please do something? thnks
