### ISSUE TITLE
TypeError when running opendrop

### ISSUE THREAD

**Issue by fluzz142857** [seemoo-lab/opendrop#16]
I installed opendrop with the command `pip3 install opendrop --user` and then ran it with `opendrop find`, but I'm getting this error:

```
C:\>opendrop find
Traceback (most recent call last):
  File "c:\program files (x86)\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\Scripts\opendrop.exe\__main__.py", line 5, in <module>
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\opendrop\cli.py", line 30, in <module>
    from .client import AirDropBrowser, AirDropClient
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\opendrop\client.py", line 26, in <module>
    import libarchive
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\<user>\AppData\Roaming\Python\Python37\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "c:\program files (x86)\python\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "c:\program files (x86)\python\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
```

As a side note, thank you so, so much for making this! I've been looking for a way to share files between my devices in an AirDrop-like fashion ever since I started using a Windows machine.

**Comment by schmittner** [comment]
We do not (and will not) provide Windows support, see my answer in #3.
