### ISSUE TITLE
OpenDrop failing after installation

### ISSUE THREAD

**Issue by Kelechukwu** [seemoo-lab/opendrop#17]
After following the setup instructions in the README . Opendrop fails to run with the following error:

`MacBook-Pro-55:open source seniorconsultant$ opendrop
read format "lha" is not supported
read format "7zip" is not supported
read format "warc" is not supported
read format "cab" is not supported
read format "rar" is not supported
read filter "bzip2" is not supported
read filter "none" is not supported
read filter "gzip" is not supported
read filter "compress" is not supported
read filter "lzop" is not supported
read filter "lzma" is not supported
read filter "xz" is not supported
read filter "rpm" is not supported
read filter "all" is not supported
read filter "uu" is not supported
read filter "lzip" is not supported
read filter "grzip" is not supported
read filter "lrzip" is not supported
read filter "lz4" is not supported
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/opendrop", line 11, in <module>
    load_entry_point('opendrop==0.10.1', 'console_scripts', 'opendrop')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opendrop/cli.py", line 30, in <module>
    from .client import AirDropBrowser, AirDropClient
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opendrop/client.py", line 26, in <module>
    import libarchive
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/libarchive/ffi.py", line 184, in <module>
    c_int, check_int)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fe5fd53d940, archive_read_open_filename_w): symbol not found
MacBook-Pro-55:open source seniorconsultant$ which opendrop
/Library/Frameworks/Python.framework/Versions/3.7/bin/opendrop
MacBook-Pro-55:open source seniorconsultant$ rm -rf /Library/Frameworks/Python.framework/Versions/3.7/bin/opendrop
MacBook-Pro-55:open source seniorconsultant$ which opendrop
MacBook-Pro-55:open source seniorconsultant$ pip3 install ./opendrop
Processing ./opendrop
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from opendrop==0.10.1) (2.21.0)
Requirement already satisfied: fleep in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from opendrop==0.10.1) (1.0.1)
Requirement already satisfied: ifaddr in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from opendrop==0.10.1) (0.1.6)
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from opendrop==0.10.1) (6.1.0)
Requirement already satisfied: requests_toolbelt in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from opendrop==0.10.1) (0.9.1)
Requirement already satisfied: ctypescrypto in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from opendrop==0.10.1) (0.5)
Requirement already satisfied: libarchive-c in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from opendrop==0.10.1) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->opendrop==0.10.1) (1.24.2)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->opendrop==0.10.1) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->opendrop==0.10.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->opendrop==0.10.1) (2019.3.9)
Installing collected packages: opendrop
  Found existing installation: opendrop 0.10.1
    Uninstalling opendrop-0.10.1:
      Successfully uninstalled opendrop-0.10.1
  Running setup.py install for opendrop ... done
Successfully installed opendrop-0.10.1
MacBook-Pro-55:open source seniorconsultant$ opendrop
read format "warc" is not supported
read format "lha" is not supported
read format "cab" is not supported
read format "rar" is not supported
read format "7zip" is not supported
read filter "xz" is not supported
read filter "compress" is not supported
read filter "lzip" is not supported
read filter "rpm" is not supported
read filter "uu" is not supported
read filter "all" is not supported
read filter "bzip2" is not supported
read filter "gzip" is not supported
read filter "grzip" is not supported
read filter "lzop" is not supported
read filter "none" is not supported
read filter "lrzip" is not supported
read filter "lzma" is not supported
read filter "lz4" is not supported
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/opendrop", line 11, in <module>
    load_entry_point('opendrop==0.10.1', 'console_scripts', 'opendrop')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opendrop/cli.py", line 30, in <module>
    from .client import AirDropBrowser, AirDropClient
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/opendrop/client.py", line 26, in <module>
    import libarchive
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/libarchive/ffi.py", line 184, in <module>
    c_int, check_int)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7f810a401140, archive_read_open_filename_w): symbol not found`

**Comment by schmittner** [comment]
It seems like `libarchive` is not installed

**Comment by schmittner** [comment]
Closing this due to inactivity.
