### ISSUE TITLE
Encountered wrong when using the opendrop in terminal

### ISSUE THREAD

**Issue by matthewszeto** [seemoo-lab/opendrop#20]
$ opendrop
Traceback (most recent call last):
  File "/usr/local/bin/opendrop", line 6, in <module>
    from opendrop.cli import main
  File "/usr/local/lib/python3.7/site-packages/opendrop/cli.py", line 30, in <module>
    from .client import AirDropBrowser, AirDropClient
  File "/usr/local/lib/python3.7/site-packages/opendrop/client.py", line 32, in <module>
    from .util import AirDropUtil, AbsArchiveWrite
  File "/usr/local/lib/python3.7/site-packages/opendrop/util.py", line 30, in <module>
    from libarchive import ffi
  File "/usr/local/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/opt/libarchive/lib/libarchive.dylib, 6): image not found

**Comment by schmittner** [comment]
Consult the README. You need to have `libarchive` installed (duplicate #19)
