### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'openssl': 'openssl'

### ISSUE THREAD

**Issue by Donokami** [seemoo-lab/opendrop#31]
I'm using Termux on Android 9.0, and I got this issue:
```
$ opendrop find
Key file or certificate does not exist
Create new self-signed certificate in /data/data/com.termux/files/home/.opendrop/keys
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/opendrop", line 10, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/opendrop/cli.py", line 38, in main
    AirDropCli(sys.argv[1:])
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/opendrop/cli.py", line 65, in __init__
    debug=args.debug, interface=args.interface)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/opendrop/config.py", line 98, in __init__                           self.create_default_key()                                       File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/opendrop/config.py", line 110, in create_default_key
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 488, in run                                                  with Popen(*popenargs, **kwargs) as process:
  File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)                             File "/data/data/com.termux/files/usr/lib/python3.7/subprocess.py", line 1549, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'openssl': 'openssl'
```
My openssl version is 1.1.

**Comment by schmittner** [comment]
We currently do not support the Android platform.

**Comment by LigionBob** [comment]
I was able to get this working by installing `openssl-tools`.
`
.

**Comment by 93Pd9s8Jt** [comment]
pkg install openssl-tool worked for me
