### ISSUE TITLE
libcrypto CMS functionality error

### ISSUE THREAD

**Issue by siperialainen** [seemoo-lab/opendrop#42]
I tried both installing opendrop using "pip3 install opendrop" and "pip3 install ./opendrop" where ./opendrop is the most recent version from repository, but I'm facing this error:

```
Traceback (most recent call last):
  File "/usr/bin/opendrop", line 5, in <module>
    from opendrop.cli import main
  File "/usr/lib/python3.7/site-packages/opendrop/cli.py", line 28, in <module>
    from .client import AirDropBrowser, AirDropClient
  File "/usr/lib/python3.7/site-packages/opendrop/client.py", line 32, in <module>
    from .util import AirDropUtil, AbsArchiveWrite
  File "/usr/lib/python3.7/site-packages/opendrop/util.py", line 30, in <module>
    from ctypescrypto import cms, x509, pkey, oid
  File "/usr/lib/python3.7/site-packages/ctypescrypto/cms.py", line 24, in <module>
    raise OSError("libcrypto lacks CMS functionality. Try using different libcrypto")
OSError: libcrypto lacks CMS functionality. Try using different libcrypto
```
I'm using Python 3.7.3 and ctypescrypto 0.5 under OpenSuse Tumbleweed.
So is this a known error or should the code be updated somehow?

**Comment by schmittner** [comment]
Well, the error message gives it away: „libcrypto lacks CMS functionality. Try using different libcrypto.“ I won‘t be able to help here.
