### ISSUE TITLE
"No buffer space available" on find and receive

### ISSUE THREAD

**Issue by yeralin** [seemoo-lab/opendrop#54]
System information:
  • Operating system: MacOS Catalina 10.15.7
  • Device: MacBook Pro (16-inch, 2019)

Steps to reproduce:
```
~ opendrop find
Looking for receivers. Press enter to stop ...
Error sending through socket 4
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2889, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
OSError: [Errno 55] No buffer space available
```
```
~ opendrop receive
Announcing service: host 3c22fbf03a1f.ant.amazon.com, address fe80::7446:c4ff:fe51:d986, port 8771
Error sending through socket 4
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2889, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
OSError: [Errno 55] No buffer space available
Starting HTTPS server
```

Expected results: Find new devices and/or receive incoming payload
Actual results: Catching `OSError: [Errno 55] No buffer space available` errors upon execution.

Things tried:
1) Increasing datagram size:
```
sudo sysctl -w net.inet.udp.maxdgram=655350
net.inet.udp.maxdgram: 9216 -> 655350
```
No effect.

**Comment by yeralin** [comment]
Any ideas on this? :)

**Comment by schmittner** [comment]
I have no issues on macOS 10.15.7 with a MacBook Pro 2020.

Are you running on a clean install?

**Comment by yeralin** [comment]
Problem went away with a recent Mac update

**Comment by acheong08** [comment]
Got something to do with VPNs I think

**Comment by acheong08** [comment]
Same error here whenever a proxy or VPN is being used
