### ISSUE TITLE
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.

### ISSUE THREAD

**Issue by santiagodemierre** [seemoo-lab/opendrop#55]
opendrop receive

Traceback (most recent call last):
  File "/home/santiago/.local/bin/opendrop", line 8, in <module>
    sys.exit(main())
  File "/home/santiago/.local/lib/python3.6/site-packages/opendrop/cli.py", line 36, in main
    AirDropCli(sys.argv[1:])
  File "/home/santiago/.local/lib/python3.6/site-packages/opendrop/cli.py", line 75, in __init__
    self.receive()
  File "/home/santiago/.local/lib/python3.6/site-packages/opendrop/cli.py", line 156, in receive
    self.server = AirDropServer(self.config)
  File "/home/santiago/.local/lib/python3.6/site-packages/opendrop/server.py", line 54, in __init__
    'Make sure that `owl` is running.'.format(self.config.interface))
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.

opendrop find
Looking for receivers. Press enter to stop ...
Traceback (most recent call last):
  File "/home/santiago/.local/bin/opendrop", line 8, in <module>
    sys.exit(main())
  File "/home/santiago/.local/lib/python3.6/site-packages/opendrop/cli.py", line 36, in main
    AirDropCli(sys.argv[1:])
  File "/home/santiago/.local/lib/python3.6/site-packages/opendrop/cli.py", line 77, in __init__
    self.find()
  File "/home/santiago/.local/lib/python3.6/site-packages/opendrop/cli.py", line 96, in find
    self.browser = AirDropBrowser(self.config)
  File "/home/santiago/.local/lib/python3.6/site-packages/opendrop/client.py", line 44, in __init__
    'Make sure that `owl` is running.'.format(config.interface))
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.

**Comment by BingliangLI** [comment]
I have the same problem.
I also find a similar issue [here](https://github.com/KishanBagaria/AirDoS/issues/1)
```
PS C:\Users\lbing> opendrop find
Key file or certificate does not exist
Create new self-signed certificate in C:\Users\lbing/.opendrop\keys
Looking for receivers. Press enter to stop ...
Traceback (most recent call last):
  File "c:\users\lbing\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lbing\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lbing\anaconda3\Scripts\opendrop.exe\__main__.py", line 7, in <module>
  File "c:\users\lbing\anaconda3\lib\site-packages\opendrop\cli.py", line 36, in main
    AirDropCli(sys.argv[1:])
  File "c:\users\lbing\anaconda3\lib\site-packages\opendrop\cli.py", line 77, in __init__
    self.find()
  File "c:\users\lbing\anaconda3\lib\site-packages\opendrop\cli.py", line 96, in find
    self.browser = AirDropBrowser(self.config)
  File "c:\users\lbing\anaconda3\lib\site-packages\opendrop\client.py", line 43, in __init__
    raise RuntimeError('Interface {} does not have an IPv6 address. '
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.
PS C:\Users\lbing> opendrop receive
Key file or certificate does not exist
Create new self-signed certificate in C:\Users\lbing/.opendrop\keys
Traceback (most recent call last):
  File "c:\users\lbing\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lbing\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lbing\anaconda3\Scripts\opendrop.exe\__main__.py", line 7, in <module>
  File "c:\users\lbing\anaconda3\lib\site-packages\opendrop\cli.py", line 36, in main
    AirDropCli(sys.argv[1:])
  File "c:\users\lbing\anaconda3\lib\site-packages\opendrop\cli.py", line 75, in __init__
    self.receive()
  File "c:\users\lbing\anaconda3\lib\site-packages\opendrop\cli.py", line 156, in receive
    self.server = AirDropServer(self.config)
  File "c:\users\lbing\anaconda3\lib\site-packages\opendrop\server.py", line 53, in __init__
    raise RuntimeError('Interface {} does not have an IPv6 address. '
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.
```

**Comment by boaz-warshawsky** [comment]
@santiagodemierre Make sure that your mac WIFI is on

**Comment by santiagodemierre** [comment]
I was trying to connect iphone 6 to my linux computer
I checked the wifi connection and it's on. They are both on the same
network and they are connected via bluetooth

**Comment by BingliangLI** [comment]
Hi, thanks in advance.
I’m using Opendrop on Windows 10 and iPad Pro 2020(but obviously the problem is with my PC).
I checked my IPv6 setting and it’s not enabled, however, after I enabled it (and restarted my PC) I still have the same problem 🤔
I checked my proxy it doesn’t block IPv6 address.
Is this problem related to IPv6 access?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Boaz Warshawsky<mailto:notifications@github.com>
发送时间: 2020年10月21日 14:53
收件人: seemoo-lab/opendrop<mailto:opendrop@noreply.github.com>
抄送: Bingliang Li<mailto:bingliangl@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [seemoo-lab/opendrop] RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running. (#55)


@santiagodemierre<https://github.com/santiagodemierre> Make sure that your mac WIFI is on

**Comment by schmittner** [comment]
Please check the requirements regarding AWDL. OpenDrop currently **requires** to run on either **macOS or Linux**. On Linux, you will have to run our [OWL](https://github.com/seemoo-lab/owl) implementation (this is what the error message is telling you @santiagodemierre)
