### ISSUE TITLE
A program error?

### ISSUE THREAD

**Issue by Roger-Wang-Shenzhen** [seemoo-lab/opendrop#59]
Here is the error message, it seems that there are errors in the code, I've tried to install version 0.12.3 and 0.12.2, and there is the same errors.

> C:\user>opendrop
Traceback (most recent call last):
  File "c:\user\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\user\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\user\AppData\Local\Programs\Python\Python38\Scripts\opendrop.exe\__main__.py", line 4, in <module>
  File "c:\user\appdata\local\programs\python\python38\lib\site-packages\opendrop\cli.py", line 28, in <module>
    from .client import AirDropBrowser, AirDropClient
  File "c:\user\appdata\local\programs\python\python38\lib\site-packages\opendrop\client.py", line 30, in <module>
    import libarchive
  File "c:\user\appdata\local\programs\python\python38\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "c:\user\appdata\local\programs\python\python38\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "c:\user\appdata\local\programs\python\python38\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "c:\user\appdata\local\programs\python\python38\lib\ctypes\__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "c:\user\appdata\local\programs\python\python38\lib\ctypes\__init__.py", line 363, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by schmittner** [comment]
Please read the requirements section of the README. This particular error occurs because you apparently have not installed `libarchive`. In any case, OpenDrop is not supported on Windows.

**Comment by ra1n08** [comment]
https://gnuwin32.sourceforge.net/packages/libarchive.htm
try this, it libArchive for windows, i think it work :3
