### ISSUE TITLE
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running

### ISSUE THREAD

**Issue by Foro38** [seemoo-lab/opendrop#61]
~ opendrop find
Looking for receivers. Press Ctrl+C to stop ...
Traceback (most recent call last):
  File "/usr/bin/opendrop", line 8, in <module>
    sys.exit(main())
  File "/home/foro/.local/lib/python3.9/site-packages/opendrop/cli.py", line 36, in main
    AirDropCli(sys.argv[1:])
  File "/home/foro/.local/lib/python3.9/site-packages/opendrop/cli.py", line 98, in __init__
    self.find()
  File "/home/foro/.local/lib/python3.9/site-packages/opendrop/cli.py", line 117, in find
    self.browser = AirDropBrowser(self.config)
  File "/home/foro/.local/lib/python3.9/site-packages/opendrop/client.py", line 43, in __init__
    raise RuntimeError(
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running

**Comment by schmittner** [comment]
It's what the error message tells you. If you run OpenDrop on a Linux machine, you need to run `owl` in parallel. Please check out the README.
