### ISSUE TITLE
Error installing on Raspberry Pi 3

### ISSUE THREAD

**Issue by ElevonsJKeloids** [seemoo-lab/opendrop#63]
Hi, I'm unable to install Opendrop on my Raspberry Pi.
Here's the issue I encounter after running `sudo pip3 install ./opendrop`:

```
Processing ./opendrop
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-sxe2i944-build/setup.py", line 1, in <module>
        from opendrop import __version__
      File "/tmp/pip-sxe2i944-build/opendrop/__init__.py", line 29
        os.environ["DYLD_LIBRARY_PATH"] = f"{dyld_path}:{archive_path}"
                                                                      ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-sxe2i944-build/

```

**Comment by schmittner** [comment]
Looks like you are running a Python version that does not support f-strings, i.e., 3.5 and earlier. You can check your version via `python3 --version`.

**Comment by ElevonsJKeloids** [comment]
I can confirm that after [building Python 3.6](https://josefmtd.com/2018/08/07/install-python-3-6-on-raspbian-english/) on my Pi I was able to install OpenDrop! Thanks for your help.
