### ISSUE TITLE
You must specify a valid interface name.

### ISSUE THREAD

**Issue by stringcode86** [seemoo-lab/opendrop#7]
Running Ubuntu 19.04 with 5.2.8 kernel. Connected via ethernet cable. Wifi enabled but not connected to anything.

`open drop find`
`
Looking for receivers. Press enter to stop ...
Traceback (most recent call last):
  File "/home/stringcode/.local/bin/opendrop", line 10, in <module>
    sys.exit(main())
  File "/home/stringcode/.local/lib/python3.7/site-packages/opendrop/cli.py", line 38, in main
    AirDropCli(sys.argv[1:])
  File "/home/stringcode/.local/lib/python3.7/site-packages/opendrop/cli.py", line 78, in __init__
    self.find()
  File "/home/stringcode/.local/lib/python3.7/site-packages/opendrop/cli.py", line 97, in find
    self.browser = AirDropBrowser(self.config)
  File "/home/stringcode/.local/lib/python3.7/site-packages/opendrop/client.py", line 48, in __init__
    self.ip_addr, self.byte_address = AirDropUtil.get_ip_for_interface(self.ip_interface_name, ipv6=self.useIPv6)
  File "/home/stringcode/.local/lib/python3.7/site-packages/opendrop/util.py", line 229, in get_ip_for_interface
    addresses = netifaces.ifaddresses(interface_name)
ValueError: You must specify a valid interface name.`

**Comment by schmittner** [comment]
I guess you are not running OWL? OpenDrop requires the `awdl0` interface to be present. You can find a complete howto [here](https://owlink.org/2019/05/16/howto-use-airdrop-on-raspberry-pi-3.html).

**Comment by stringcode86** [comment]
Thank you! OWL fixed the issue
