### ISSUE TITLE
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.

### ISSUE THREAD

**Issue by JforJason101** [seemoo-lab/opendrop#72]
How do I solve this?

**Comment by legendary-cookie** [comment]
I have to specify my interface (get yours with ifconfig, probably something like wlan0) with the -i switch (opendrop -i INTERFACE)

**Comment by Sn0wfreezeDev** [comment]
Looks like AWDL was off on your device. Otherwise it should have an IPv6 address. You don't need OWL for running it on a Mac. I'd suggest to open AirDrop and see if restarts the interface. If AirDrop is also not working, you can restart your device

**Comment by BackMountainDevil** [comment]
a year later. I try again and fail.  A wired thing is that I do not have a interface named `awdl0`. I only got lo and wlan0 from command `ip addr`. My wifi card is RTL8822CE runnning on endevaourOS.

Maybe it is about WDS. 

```bash
$ opendrop find
Looking for receivers. Press Ctrl+C to stop ...
Traceback (most recent call last):
  File "/usr/bin/opendrop", line 33, in <module>
    sys.exit(load_entry_point('opendrop==0.13.0', 'console_scripts', 'opendrop')())
  File "/usr/lib/python3.10/site-packages/opendrop/cli.py", line 36, in main
    AirDropCli(sys.argv[1:])
  File "/usr/lib/python3.10/site-packages/opendrop/cli.py", line 101, in __init__
    self.find()
  File "/usr/lib/python3.10/site-packages/opendrop/cli.py", line 121, in find
    self.browser = AirDropBrowser(self.config)
  File "/usr/lib/python3.10/site-packages/opendrop/client.py", line 43, in __init__
    raise RuntimeError(
RuntimeError: Interface awdl0 does not have an IPv6 address. Make sure that `owl` is running.
```

**Comment by BackMountainDevil** [comment]
I look into cli.pyL68 

`"-i", "--interface", help="Which AWDL interface to use", default="awdl0"`

so i just need type `opendrop find -i wlan0`. this issue will be gone and got new issue
