### ISSUE TITLE
Error sending file

### ISSUE THREAD

**Issue by pvbaudin** [seemoo-lab/opendrop#88]
Just installed opendrop with pip

opendrop receive works without issue
opendrop find works without issue

opendrop send returns an error message after the receiver clicks accept, airdrop notification says file transfer was cancelled

Tried with full path and relative path, tried with simple jpg and empty file created with "touch empty"

System information:
M1 Macbook running macOS 12.1
Python version 3.9.10

tried sending file to another macbook and to the same macbook.

> Asking receiver to accept ...
> Receiver accepted
> Uploading file ...
> Exception ignored in: <function ArchiveEntry.__del__ at 0x10152fd30>
> Traceback (most recent call last):
>   File "/opt/homebrew/lib/python3.9/site-packages/libarchive/entry.py", line 51, in __del__
>     ffi.entry_free(self._entry_p)
> AttributeError: _entry_p
> Traceback (most recent call last):
>   File "/opt/homebrew/bin/opendrop", line 8, in <module>
>     sys.exit(main())
>   File "/opt/homebrew/lib/python3.9/site-packages/opendrop/cli.py", line 36, in main
>     AirDropCli(sys.argv[1:])
>   File "/opt/homebrew/lib/python3.9/site-packages/opendrop/cli.py", line 112, in __init__
>     self.send()
>   File "/opt/homebrew/lib/python3.9/site-packages/opendrop/cli.py", line 196, in send
>     if not self.client.send_upload(self.file, is_url=self.is_url):
>   File "/opt/homebrew/lib/python3.9/site-packages/opendrop/client.py", line 214, in send_upload
>     archive.add_abs_file(f, os.path.join(".", ff))
>   File "/opt/homebrew/lib/python3.9/site-packages/opendrop/util.py", line 184, in add_abs_file
>     entry = ArchiveEntry(None, entry_p)
> TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

**Comment by bodaay** [comment]
use old libarchive:
libarchive-c==2.9

**Comment by Haimonti** [comment]
I was able to send files between 

macbook running macOS 10.15
iPhone running iOS 16.12
iPad Mini 4 12.2

The problem persisted when using macbook running MacOS Ventura 13.0 (arm64). I tried compiling with different versions of libarchive (2.8 through 4.0) but no help. I installed with pip3 install opendrop libarchive-c==2.9 (or appropriate version). 

If I used the most recent version of the code from the git repo, would it work with macOS Ventura 13?

**Comment by Atemu** [comment]
Fixed by https://github.com/seemoo-lab/opendrop/pull/95
