### ISSUE TITLE
opendrop find not printing and errors Mac OS 12.3.1

### ISSUE THREAD

**Issue by bentettmar** [seemoo-lab/opendrop#92]
When trying to use `opendrop find` It doesn't print anything other than the future warning that i fixed myself and when an airdrop user shows up in the airdrop finder window it prints an error to the screen. The error that shows up is below.

```
Exception in thread zeroconf-ServiceBrowser-_airdrop._tcp-17461:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 534, in run
    self._fire_service_state_changed_event(event)
  File "/opt/homebrew/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 417, in _fire_service_state_changed_event
    self._service_state_changed.fire(
  File "/opt/homebrew/lib/python3.9/site-packages/zeroconf/_services/__init__.py", line 55, in fire
    h(**kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/zeroconf/_services/browser.py", line 178, in on_change
    getattr(listener, _ON_CHANGE_DISPATCH[state_change])(zeroconf, service_type, name)
AttributeError: 'AirDropBrowser' object has no attribute 'update_service'
```

Below is a GIF of what happens when I run `opendrop find`.
![CleanShot 2022-08-03 at 5 02 00](https://user-images.githubusercontent.com/83777519/182655961-5a262252-b06f-4498-97a6-2bcba5eb574a.gif)

I have also looked at running owl at the same time but I wasn't able to get owl working on my wifi adapter.

**Comment by bentettmar** [comment]
Just realised the logger class is part of python, maybe my python logging lib is broken.

**Comment by bentettmar** [comment]
Making my own logging class fixed it perfectly fine.
<img width="518" alt="CleanShot 2022-08-03 at 5 21 44@2x" src="https://user-images.githubusercontent.com/83777519/182659498-4d11c9a8-0784-4ff0-a496-d0d82f53bf80.png">

For other users looking for a fix to this i will create a fork with my changes.

**Comment by lucasromeiro** [comment]
Hello everyone, this happened in the first step to get the keys:

![image](https://user-images.githubusercontent.com/2086543/220122693-248d8527-7e56-4ffd-805a-50d6554b6e27.png)


I continued the tutorial normally, but when I run the make command I get this error:

![image](https://user-images.githubusercontent.com/2086543/220122869-6bb240a3-a9cc-489c-8232-8946c903fa0f.png)


Can someone help me?

My MAC is a MacStudio with M1 Max and MAC OS 13.1 (22C65) (ventura).


Please, help...
